### ISSUE TITLE
<open file ... > is not JSON serializable

### ISSUE THREAD

**Issue by bogdanf** [mk-fg/txonedrive#1]
I consistently get the following error when using the `api.put` function (even when running the tests in `txonedrive/api_v5.py`). Other API functions work OK.

```
Unhandled Error
Traceback (most recent call last):
  File "/Users/bogdanf/.pyenv/versions/onedrive/lib/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/Users/bogdanf/.pyenv/versions/onedrive/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/Users/bogdanf/Projects/Onedrive backup/python-onedrive-master/txonedrive/api_v5.py", line 429, in __call__
    try: res = yield self.request(api_url(), **kwz)
  File "/Users/bogdanf/.pyenv/versions/onedrive/lib/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Users/bogdanf/.pyenv/versions/onedrive/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/Users/bogdanf/Projects/Onedrive backup/python-onedrive-master/txonedrive/api_v5.py", line 357, in request
    body = FileBodyProducer(io.BytesIO(json.dumps(data)), timer=timeout)
  File "/Users/bogdanf/.pyenv/versions/2.7.9/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/Users/bogdanf/.pyenv/versions/2.7.9/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/bogdanf/.pyenv/versions/2.7.9/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/bogdanf/.pyenv/versions/2.7.9/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
exceptions.TypeError: <open file 'README.md', mode 'rb' at 0x103f68a50> is not JSON serializable
INFO:twisted:Main loop terminated.
```

I run it under Python 2.7.9, with the following packages installed :

```
cffi (0.8.6)
characteristic (14.3.0)
chardet (2.3.0)
cryptography (0.7.2)
enum34 (1.0.4)
pip (6.0.6)
pudb (2014.1)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pycparser (2.10)
Pygments (2.0.1)
pyOpenSSL (0.14)
python-onedrive (15.1.5)
PyYAML (3.11)
requests (2.5.1)
service-identity (14.0.0)
setuptools (11.3.1)
six (1.9.0)
Twisted (14.0.2)
urwid (1.3.0)
zope.interface (4.1.2)
```

**Comment by mk-fg** [comment]
Yeah, it's not a random bug, but rather a consequence of neglect to keep this module up to date with python-onedrive.
As a workaround, I think you can downgrade python-onedrive to roughly same version (both versions are in a "year.month.commits-this-month" format) as txonedrive - i.e. 14.05.something or even 13.06.something (time of the last non-null change).

**Comment by bogdanf** [comment]
Thanks, it worked, even 14.6.x seems to work. The only (and important) issue now it's that in 14.6 uploading large files throws an error (which isn't a surprise).

So, looking forward your updates to txonedrive.

**Comment by mk-fg** [comment]
Probably not relevant anyway, but I've added deprecation notice and all that.
MS made proper python module for their new API, which iirc even had async stuff in it, so by now there should be no reason to use this module ever.
